config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'projects#index'
  resources :projects
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ActiveRecord::Base

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @projects = Project.all
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      flash[:notice] = 'Projekat je uspesno kreiran.'
      redirect_to project_path(@project)
    else
      render 'new'
    end
  end

  def show
    @project = Project.find(params[:id])
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    if @project.update(project_params)
      flash[:notice] = 'Projekat je uspesno azuriran.'
      redirect_to project_path(@project)
    else
      render 'edit'
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    flash[:notice] = 'Projekat je uspesno obrisan.'
    redirect_to projects_path
  end

  private
  def project_params
    params.require(:project).permit(:naziv, :trajanje, :vrsta, :sredstva, :oprema)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSeminarski</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <% flash.each do |ime, poruka| %>
      <ul>
        <li><%= poruka %></li>
      </ul>
  <% end %>

    <%= yield %>
  </body>
</html>

app/views/projects/edit.html.erb
<h1>Azuriraj projekat</h1>

<% if @project.errors.any? %>
    <h2>Projekat se ne moze azurirati zbog sledecih gresaka: </h2>
    <ul>
      <% @project.errors.full_messages.each do |poruka| %>
          <li><%= poruka %></li>
      <% end %>
    </ul>
<% end %>

<%= form_for @project do |f| %>

    <p>
      <%= f.label :naziv %><br/>
      <%= f.text_field :naziv %>
    </p>

    <p>
      <%= f.label :trajanje %><br/>
      <%= f.text_field :trajanje %>
    </p>

    <p>
      <%= f.label :vrsta %><br/>
      <%= f.text_field :vrsta %>
    </p>

    <p>
      <%= f.label 'sredstva (U dinarima)' %><br/>
      <%= f.text_field :sredstva %>
    </p>

    <p>
      <%= f.label :oprema %><br/>
      <%= f.text_area :oprema %>
    </p>

    <p>
      <%= f.submit :Potvrdi %>
    </p>

<% end %>

<%= link_to 'Nazad na listu svih projekata', projects_path %>

app/views/projects/index.html.erb
<h1>Lista svih projekata: </h1>

<p>
  <%= link_to 'Kreiraj novi projekat', new_project_path %>
</p>

<table>
  <tr>
    <th>Naziv projekta</th>
  </tr>
  <% @projects.each do |projekat| %>
      <tr>
        <td><%= projekat.naziv %></td>
        <td><%= link_to 'Azuriraj', edit_project_path(projekat) %></td>
        <td><%= link_to 'Prikazi', project_path(projekat) %></td>
        <td><%= link_to 'Izbrisi', project_path(projekat), method: :delete, data: {confirm: 'Da li ste sigurni?'} %></td>
      </tr>
  <% end %>
</table>

app/views/projects/new.html.erb
<h1>Kreiraj projekat</h1>

<% if @project.errors.any? %>
    <h2>Projekat se ne moze kreirati zbog sledecih gresaka: </h2>
    <ul>
      <% @project.errors.full_messages.each do |poruka| %>
          <li><%= poruka %></li>
      <% end %>
    </ul>
<% end %>

<%= form_for @project do |f| %>

    <p>
      <%= f.label :naziv %><br/>
      <%= f.text_field :naziv %>
    </p>

    <p>
      <%= f.label :trajanje %><br/>
      <%= f.text_field :trajanje %>
    </p>

    <p>
      <%= f.label :vrsta %><br/>
      <%= f.text_field :vrsta %>
    </p>

    <p>
      <%= f.label 'sredstva (U dinarima)' %><br/>
      <%= f.text_field :sredstva %>
    </p>

    <p>
      <%= f.label :oprema %><br/>
      <%= f.text_area :oprema %>
    </p>

    <p>
      <%= f.submit :Potvrdi %>
    </p>

<% end %>

<%= link_to 'Nazad na listu svih projekata', projects_path %>

app/views/projects/show.html.erb
<h1>Projekat:</h1>

<p>
  Naziv: <%= @project.naziv %>
</p>

<p>
  Trajanje: <%= @project.trajanje %>
</p>

<p>
  Vrsta: <%= @project.vrsta %>
</p>

<p>
  Sredstva: <%= @project.sredstva %>
</p>

<p>
  Oprema: <%= @project.oprema %>
</p>

<%= link_to 'Azuriraj ovaj projekat', edit_project_path(@project) %> |

<%= link_to 'Nazad na listu svih projekata', projects_path %>